version: '3.9'

networks:
  backend:
    driver: bridge

services:
  dockerizing-pytest:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/Fortaleza
    command: ["tail", "-f", "/dev/null"]

    networks:
      - backend
